## Version  itérative

In [1]:
import numpy as np
import time
def update_Pi(K, L, Pi, lambda_val, nb_iter):
    max_ = np.trace(K@Pi.T@L@Pi)
    max_pi = Pi
    
    for i in range(nb_iter):
        tempPi = np.random.permutation(np.eye(K.shape[0])) #Changement de "randint" par "permutation" pour générer les permutions aleatoires
        tr = np.trace(K@tempPi.T@L@Pi)
        
        if tr > max_:
            max_ = tr
            max_pi = tempPi
    
    updated_pi = (1 - lambda_val) * Pi + lambda_val * max_pi
    
    return updated_pi

In [7]:
K = np.array([[1, 1, 0], [1, 1, 0], [0, 0, 1]])
L = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(10):
    Pi = update_Pi(K, L, Pi, .5, 20)
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round(Pi@K))

print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Temps d'execution :  8.767366409301758 ms
K permutations : 
[[0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]]
L : 
[[0 0 1]
 [1 1 0]
 [1 1 0]]
La trace maximale =======>  2.75


In [3]:
K = np.array([[1, 1, 0], [1, 1, 0], [0, 1, 1]])
L = np.array([[0, 1, 1], [1, 1, 0], [1, 1, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(10):
    Pi = update_Pi(K, L, Pi, .7, 20)
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round(Pi@K))
print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Temps d'execution :  13.980627059936523 ms
K permutations : 
[[0. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]]
L : 
[[0 1 1]
 [1 1 0]
 [1 1 0]]
La trace maximale =======>  3.7789982262662942


In [4]:
K = np.array([[1, 1, 0, 0], [1, 1, 0, 0], [0, 0, 1, 1], [0, 0, 1, 1]])
L = np.array([[0, 0, 1, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 1, 0, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(10):
    Pi = update_Pi(K, L, Pi, .4, 100)
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round(Pi@K))
print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Temps d'execution :  30.55882453918457 ms
K permutations : 
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
L : 
[[0 0 1 1]
 [0 0 1 1]
 [1 1 0 0]
 [1 1 0 0]]
La trace maximale =======>  3.7489912148004336


# Version avec "linear_sum_assignment" de SciPy

In [5]:
from scipy.optimize import linear_sum_assignment

def update_Pi_lsa(K, L, Pi, lambda_val):
    
    l_ind, c_ind = linear_sum_assignment(-K@Pi@L.T)
    max_pi = np.zeros_like(K)
    max_pi[l_ind, c_ind] = 1
    
    updated_pi = (1 - lambda_val) * Pi + lambda_val * max_pi.T
    
    return updated_pi


In [8]:
K = np.array([[1, 1, 0], [1, 1, 0], [0, 0, 1]])
L = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(20):
    Pi = update_Pi_lsa(K, L, Pi, .5)
    #Pi = Pi.T
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round((Pi@K)))

print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Temps d'execution :  1.9917488098144531 ms
K permutations : 
[[0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]]
L : 
[[0 0 1]
 [1 1 0]
 [1 1 0]]
La trace maximale =======>  2.816326297059277


In [109]:
K = np.array([[1, 1, 0], [1, 1, 0], [0, 1, 1]])
L = np.array([[0, 1, 1], [1, 1, 0], [1, 1, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(10):
    Pi = update_Pi_lsa(K, L, Pi, .5)
    #Pi = Pi.T
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round(Pi@K))
print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Temps d'execution :  0.0 ms
K permutations : 
[[0. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]]
L : 
[[0 1 1]
 [1 1 0]
 [1 1 0]]
La trace maximale =======>  3.7775611877441406


In [110]:
K = np.array([[1, 1, 0, 0], [1, 1, 0, 0], [0, 0, 1, 1], [0, 0, 1, 1]])
L = np.array([[0, 0, 1, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 1, 0, 0]])
Pi = np.eye(K.shape[0]) 
start = time.time()
for i in range(10):
    Pi = update_Pi_lsa(K, L, Pi, .4)
    #Pi = Pi.T
end = time.time()

print("Pi = \n")
print(np.round(Pi))

print("Temps d'execution : ",(end-start) * 10**3, "ms")
print('K permutations : ')
print(np.round(Pi@K))
print('L : ')
print(L)

print("La trace maximale =======> ", np.trace(K @ Pi.T @ L @ Pi))

Pi = 

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
Temps d'execution :  6.521463394165039 ms
K permutations : 
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
L : 
[[0 0 1 1]
 [0 0 1 1]
 [1 1 0 0]
 [1 1 0 0]]
La trace maximale =======>  3.748991214800433
